### PR TITLE
Enhancements to Anime Info Page with New Features and UI Improvements (Desktop)

### PR DESCRIPTION
**Pull request by swargaraj**
Enhanced Anime Info Page for Desktop.

- Updated database schema
- Implemented sign-up prompt dialog [#55](https://github.com/mochi-stream/mochi/issues/55)
- Added graphql queries & types
- Design layout changed
- Added recommendations and related anime sections
- Included characters and staff lists
- Added video player for Streaming from [dev/video-player-integration](https://github.com/mochi-stream/mochi/tree/dev/video-player-integration)

[Preview 1](https://mochi-mbamhwu74-rcdu6bgx8qqfmlv3s-projects.vercel.app/anime/101921) | [Preview 2](https://mochi-mbamhwu74-rcdu6bgx8qqfmlv3s-projects.vercel.app/anime/21)

### CODE REVIEW

**Comment by swargaraj** [comment]
@MSoup @jackli921 Check this out

**Comment by jackli921** [comment]
This PR includes a lot of changes. I'm scanning through it but I don't think I know enough about the framework and TS used to be able to provide constructive feedback. At least not yet. I think @MSoup will be able to provide some input.

**Comment by jackli921** [comment]
Tested the newly added features on vercel auto deploy. Everything looks good to me. 

Only thing I noticed is the show text details may need repositioning on mobile devices. 
image

**Comment by jackli921** [comment]
How do you test the video player feature on Vercel's auto-deploy?
image

**Comment by swargaraj** [comment]
> Tested the newly added features on vercel auto deploy. Everything looks good to me.
> 
> Only thing I noticed is the show text details may need repositioning on mobile devices. image

This PR is only for the desktop devices. I am rapidly developing other pages. After that I will make all pages responsive in one PR

**Comment by swargaraj** [comment]
> How do you test the video player feature on Vercel's auto-deploy? image

The last commit cannot be actually viewed on the vercel yet. Only the video player component files were mergered from [dev/video-player-integration](https://github.com/mochi-stream/mochi/tree/dev/video-player-integration) in that commit and it was working perfectly fine [there](https://mochi-git-dev-video-player-in-3293a5-swargarajbhowmiks-projects.vercel.app/stream/masamune-kuns-revenge-4133/watch/36637)

**Comment by swargaraj** [comment]
So basically I created graphql queries & fragments in the graphql folder that fetches the anime information from anilist's graphql api and display them in the /app/anime/[id]/page.tsx. Most of the commits are for design improvements.

Some backlogs are there like to make it suitable for smaller devices and also some with "TODO:" in the code which will be soon in future.

**Pull request merged**
