### PR TITLE
Enhancements and New Features: Stream Page, Comments, Search, Collections, and Mobile Responsiveness

### PR DESCRIPTION
**Pull request by swargaraj**
This pull request introduces several significant updates and features to the application:

[Preview](https://mochi-preview.vercel.app/) (Images may not load :(, vercel's monthly optimized image quota is full)

1. **Stream Page Creation**: A new stream page has been created to enhance the viewing experience (Currently it's doing 3 requests so bit slow, we will change to 2 request soon).
2. **Comments Feature**: Implemented a commenting system on the stream page, including functionality for creating and deleting comments.
3. **Emoji Picker**: Added an emoji picker to the comment box to improve user interaction and expression.
4. **Autocomplete Search**: Integrated an autocomplete search feature to streamline finding content.
5. **Search Filter**: Added search filters to refine search results based on user input.
6. **Episodes List**: Incorporated an episodes list within the anime information section to provide detailed episode data.
7. **Next Episode Estimate**: Displayed an estimate for when the next episode will air, enhancing user anticipation.
8. **Collection Feature**: Introduced a collection feature for users to organize their watched or planned anime.
9. **Meta Pages**: Added meta pages for Privacy Policy and Terms of Service to comply with legal requirements.
10. **Episode Release Subscriptions**: Enabled subscription options for users to get notified about new episode releases.
11. **Mobile Responsiveness**: Made the site mobile-responsive to ensure a seamless experience across devices.
12. **User Anime List**: Added a section in profile pages for users to view their personal anime list.
13. **Basic Animations**: Implemented basic animations to improve the visual appeal and user experience.

Branches currently being merged: [#streaming-page](https://github.com/mochi-stream/mochi/tree/streaming-page) [#comment-feature](https://github.com/mochi-stream/mochi/tree/comment-feature) [#search-page](https://github.com/mochi-stream/mochi/tree/search-page)

## Gallery
Preview 1
Preview 2
Preview 3
Preview 4
Preview 5
Preview 6

### CODE REVIEW

**Comment by swargaraj** [comment]
Too many commits, so just review it blindly, It will auto merge.

**Comment by MSoup** [comment]
Great work, I think the UI looks quite nice

Some comments from me:

- I clicked Login and authenticated with Google
- Upon redirecting to the landing page, a modal asked for me to input my username
- After inputting my username, it seems that the top right icons are in a "loading" state indefinitely

image

- The comments feature is not yet testable. In the preview URL, I see `Comments not available yet.` (tested by going to Oshi No Ko S2, then clicking 'comments')

- For the 'next episode prediction', I think it might be nice UX to look at the logged in user's timezone settings (if we want to enable this) and show the time in their local time zone. For example I am in JST but the time displayed is GMT+9.

- The shadow? on 'add to collection' is a little strange
image

- After clicking on "add to collection", the button text still says "add to collection". I wonder if it should change to say something else (such as 'update collection'?) I don't know what the best text might be.

**Comment by MSoup** [comment]
But I don't want to block you so I will approve it anyway now :)

**Comment by jackli921** [comment]
Great stuff. Functionality all works. These are just small things that can be worked in later.

* Meta Pages - The numbered heading in the privacy page skips 5 and jumps from 4 straight to 6. 
image
 
* Mobile Responsiveness - The image size on the Characters and Staff sub-pages are different from the Episodes tab and are all right-aligned. Maybe that's intended?
image

**Review by MSoup — APPROVED** [review]

**Pull request merged**
